#!/bin/sh

MY_PATH=`dirname "$0"`
MY_PATH=`( cd "${MY_PATH}" && pwd )`

echo "Copy to /usr/local/bin"
sudo cp -rf ${MY_PATH}/remoteAppStandAlone /usr/local/bin/remoteAppStandAlone

echo "Make script executable"
sudo chmod u+x /usr/local/bin/remoteAppStandAlone

echo "Copy to /etc/systemd/system/remoteAppStandAlone.service"
sudo cp -rf ${MY_PATH}/remoteAppStandAlone.service /etc/systemd/system/remoteAppStandAlone.service

echo "Enable service"
sudo systemctl enable remoteAppStandAlone

echo "Start service"
sudo systemctl start remoteAppStandAlone