#!/bin/sh

start() {
  echo 'Start RemoteAppStandAlone'
  MYPATH=`ls -l /usr/local/bin/remoteAppStandAlone | awk '{print $NF}'`
  MYPATH=`dirname ${MYPATH}`
  MYPATH=`dirname ${MYPATH}`
  cd ${MYPATH}
  NODE_ENV=production node ./server/server
}

stop() {
  echo 'Stop RemoteAppStandAlone'
  echo '@todo'
}

case $1 in
  start|stop) "$1" ;;
esac

exit 0
