#!/bin/sh

echo "Disable service"
sudo systemctl disable remoteAppStandAlone

echo "Stop service"
sudo systemctl stop remoteAppStandAlone

echo "Remove bin"
sudo rm /usr/local/bin/remoteAppStandAlone

echo "Remove unit file"
sudo rm /etc/systemd/system/remoteAppStandAlone.service